version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: postgres
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: always
  backend:
    build: .
    ports:
      - "3001:3001"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USER: postgres
      DB_PASSWORD: mysecretpassword
      DB_DATABASE: postgres
      DB_PORT: 5432
      APP_PORT: 3001
    env_file:
      - .env
    restart: always

volumes:
  db_data: